name: Test Backend
on:
  push:
    paths: 
     - backend/**
  pull_request:
    branches:
      - main
    paths: 
     - backend/**

defaults:
  run:
    working-directory: backend 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Start local emulator suite and test
        uses: w9jds/firebase-action@master
        with:
          args:  emulators:exec --only firestore test.sh
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HUSFRED_B5E27 }}
          PROJECT_PATH: backend
          FIRESTORE_EMULATOR_HOST: localhost:8090
