name: Test Backend
on:
  push:
    paths: 
     - backend/**
  pull_request:
    branches:
      - main
    paths: 
     - backend/**

defaults:
  run:
    working-directory: backend 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache firebase emulators
        uses: actions/cache@v1
        with:
          path: /github/home/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('emulator-cache/**') }}
        continue-on-error: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install Firebase Tools
        run: sudo npm install -g firebase-tools 
        
      - name: Start local emulator suite
        run: firebase emulators:exec --only firestore "go test"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HUSFRED_B5E27 }}
          PROJECT_PATH: backend
          FIRESTORE_EMULATOR_HOST: localhost:8090

