name: Test Backend
on:
  push:
    paths: 
     - backend/**
  pull_request:
    branches:
      - main
    paths: 
     - backend/**

defaults:
  run:
    working-directory: backend 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set environment variables
      - run: export GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.FIREBASE_SERVICE_ACCOUNT_HUSFRED_B5E27 }}
      - name: Test
        run: go test
