name: Test Backend
on:
  push:
    paths: 
     - backend/**
  pull_request:
    branches:
      - main
    paths: 
     - backend/**

defaults:
  run:
    working-directory: backend 

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: key.json
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
            version: '270.0.0'
            service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo -n ${{ secrets.GCP_SA_KEY }} | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
      - name: Test
        run: go test
