name: Build Frontend
on:
  push:
    branches:
      - main
    paths: 
     - frontend/**
  pull_request:
    branches:
      - main
    paths: 
     - frontend/**

defaults:
  run:
    working-directory: frontend 
    
name: Build frontend
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: frontend/dist
