name: Build and Deploy Frontend
on:
  push:
    branches:
      - main
    paths: 
     - frontend/**
defaults:
  run:
    working-directory: frontend 
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
      - name: Install Dependencies
        run: flutter pub get
      - name: Build
        run: flutter build web
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: frontend/build/web
          
          
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: frontend/build/web
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HUSFRED_B5E27 }}
          PROJECT_PATH: frontend
